server:
  port: 8081
  servlet:
    context-path: /admin

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_db?serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        properties:
          hibernate.format_sql: true
          hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

app:
  zuul-server: http://localhost:8091
  import:
    files-check-rate: 2000
    csv-product-dir: product-import