server:
  port: 8091

spring:
  application:
    name: zuul-server

zuul:
  ignoredServices: "*"
  routes:
    picture-service:
      path: /picture/**
      serviceId: picture-service
    stock-service:
      path: /stock/**
      serviceId: stock-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
